vlang/vls

- README.md
- Remove old comments
- Change the command to build VLS
- The latest `master` version of vscode-vlang isn't required anymore, the latest release includes VLS support
> readme: update for new repo

- vls/diagnostics.v
- vls/general.v
- vls/text_synchronization.v
- vls/vls.v
- vls/workspace.v
This reduces the memory consumption of VLS from a whopping ~180mb for simple 5-keystroke change to only 10.7mb by parsing builtin once on initialization and manual free-ing to some parts of the server
> text_sync: improve parsing flow

- tests/general_test.v
- vls/vls.v
As the title says, the server should immediately exit without waiting for the `exit` notification. The reason is stated on the code
> vls: exit immediately on shutdown

- vls/vls.v
this prevents an error that said: no fn main defintion.
> vls: add is_shared to preferences to prevent error

- vls/features.v
- vls/general.v
- vls/text_synchronization.v
- vls/vls.v
adds workspace directory to lookup paths.
Fixes this:
> add workspace path to lookup paths

- README.md
- lsp/capabilities.v
- lsp/folding_range.v
- vls/features.v
- vls/general.v
- vls/general_test.v
- vls/tests/folding_range_test.v
- vls/tests/test_files/folding_range/comment_skip.vv
- vls/tests/test_files/folding_range/simple.vv
- vls/vls.v
Add support for folding range as part of LSP spec. Closes #74 .
> vls: implement textDocument/foldingRange

- vls/general.v
- vls/general_test.v
- vls/vls.v
Extension of #58. This PR adds the hover feature to the `default_features_list` and changes the value of `hover_provider` in the `ServerCapabilities` based on the `ls.enabled_features` field
> vls: properly enable hover feature

- vls/general.v
- vls/text_synchronization.v
- vls/vls.v
Fixing memory leaks from table and some arrays not being freed between two updates
It **doesn't solve every** memory leaks,
There is still a considerable amount of leaks which are attributed to inner V AST/Parser/Scanner modules. Most of them are unfreed references and arrays.
> vls: table freeing for slight memory leak improvement

- vls/text_synchronization.v
Fix problem with an infinite loop because of multiple same modules being imported and parsed
> vls: cleaning files to be parsed in recursivity to avoid infinite loop

- vls/features.v
- vls/vls.v
Initial steps towards #81 
Currently, <kbd>Ctrl</kbd> + clicking on an identifier will show a notification. This is to confirm that the correct node is being recognised and find cases that are misidentified.
We need to work a bit on tree traversal using tree-sitter before we can extract the location where the identifiers are defined. We'll support the current file first, then the current module, then external modules.
> Add preliminary support for "go to definition"

- vls/features.v
- vls/vls.v
Sorry for the large diff set 😅. It was kinda hard to avoid due to the amount of fixes I had to keep implementing one after another.
Here's a summary of the changes:
- converted many calls to `position_to_lsp_range` (which no longer exists) to their counterpart with `tsrange_to_lsp_range`. I wrapped the `start_point` and `end_point` fields in `lsp_pos_to_tspoint` so that we can maintain compatibility with the rest of the APIs being used.
- added fields `source` and `tree` to `HoverConfig`
- temporarily uncommented `tables` field in `vls.v` since its absence causes many errors with a lot of the hover code. I think `tables` is technically obsolete now, but in order to not use it, we'll need to rewrite a lot of code to work without it.
- perhaps a few other minor things I've forgotten 🥴
If …
> Initial work on textDocument/hover support

- vls/features.v
This PR fix as cast error with the new if smartcast multi conds.
```
vls/features.v:373:24: error: cannot cast non-sum type `v.ast.Ident` using `as`
371 |             // symbols of that module.
372 |             if expr.expr_type == 0 && expr.expr is ast.Ident {
373 |                 ident := expr.expr as ast.Ident
|                                    ~~
374 |                 if ident.name !in cfg.modules_aliases {
375 |                     return completion_items
```
> features: fix as cast error with the new if smartcast multi conds

- lsp/folding_range.v
- vls/features.v
- vls/vls.v
Currently, this is almost working--i.e., there are folding ranges appearing for code in the files, but the ranges aren't appearing in the right places.
Also, I created a new function in `positions.v` to ensure compatibility with appending to the `folding_ranges` variable used in `folding_range()`, because `lsp.FoldingRange` is a different type than `lsp.Range` and it has different fields.
> Initial work on textDocument/foldingRange

- analyzer/symbol_registration.v
- vls/features.v
- vls/general_test.v
- vls/tests/document_symbols_test.v
- vls/tests/formatting_test.v
- vls/tests/workspace_symbols_test.v
Additionally,
- it updates the expected positions in the test file
- it fixes the corrupted file paths in symbols
- it also fixes tests that are failing ATM
- it refactors the feature code for reusability
> vls: re-enable document and workspace symbol tests

- analyzer/imports_misc.v
Fix warnings when running `v -gc boehm cmd/vls`
```
v -gc boehm cmd/vls
analyzer/imports_misc.v:24:36: warning: deprecated map syntax, use syntax like `{'age': 20}`
22 |         // '.freestanding'
23 |     ]
24 |     os_file_specific_suffix_indices = map{
|                                       ~~~
25 |         'windows':   [0]
26 |         'linux':     [1, 11]
```
> Fix map warning

- analyzer/store.v
- analyzer/symbol.v
- analyzer/symbol_registration.v
- vls/features.v
- vls/general.v
- vls/general_test.v
- vls/tests/implementation_test.v
- vls/tests/test_files/implementation/simple.vv
- vls/vls.v
- ~~Unit tests~~
- In some instances, a struct/type may appear to have been "implemented" an interface even though none of the fields and methods in the spec have been implemented by it.
> vls: implement textDocument/implementation

- server/vls.v
This PR remove simulate send message to avoid confusion.
> vls: remove simulate send message

- lsp/lsp.v
This PR fix uri encode error on windows, and vls can work on windows. 
Thanks @spytheman !!
```vlang
[Trace - 23:21:15] Received request 'textDocument/didOpen - (0)'.
Params: {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:///d%3A/vls/lsp/lsp.v","languageId":"v","version":1,"text":"module lsp\n\nimport os\n\ntype DocumentUri = string\n\npub fn (du DocumentUri) dir() string {\n\treturn os.dir(du)\n}\n\npub fn (du DocumentUri) path() string {\n\t$if windows {\n\t\tif du.contains('%3A') {\n\t\t\treturn du.all_after('file:///').replace('%3A', ':')\n\t\t}\n\t}\n\treturn if du.starts_with('file://') { du.all_after('file://') } else { '' }\n}\n\npub fn (du DocumentUri) dir_path() string {\n\treturn os.dir(du.path())\n}\n\npub fn document_uri_from_path(path …
```
> lsp: fix uri encode error on windows

- server/general.v
This PR fix import error with custom vroot path setting (fix #186).
> vls: fix import error with custom vroot path setting (fix #186)

- analyzer/store.v
- analyzer/symbol_registration.v
- server/diagnostics.v
- server/features.v
- server/tests/diagnostics_test.v
- server/vls.v
While PR #159 is ongoing, this PR adds diagnostics by executing `v vet`.
> server: add v.vet diagnostics

- tree_sitter/tree_sitter.v
This PR fix slice bounds out of range in get_text().
> tree_sitter: fix slice bounds out of range in get_text()

- build.vsh
This PR add '-cg' flag for easy debugging in build.vsh.
> build.vsh: add '-cg' flag for easy debugging

- cmd/vls/main.v
- cmd/vls/socket.v
This PR change socket.port type from `string` to `int`.
> socket: change socket.port type from string to int

- jsonrpc/jsonrpc.v
- server/features.v
- server/general.v
- server/general_test.v
- server/testing/testing_test.v
- server/text_synchronization.v
- server/vls.v
- server/workspace.v
As per [JSON-RPC](https://www.jsonrpc.org/specification#request_object) spec, the request ID does not have a definite type and it can be null. Currently in VLS, the ID data type is set `int` because this was used in VSCode. As seen in the latest comment in #52, JetBrain IDEs use string types as IDs and others might do the same as well. To solve this issue, the ID is parsed as a raw JSON string.
> jsonrpc, server: change request/response id to raw JSON string

- .gitignore
- server/connection_test.v
Commits are put into the PR first to avoid unnecessary changes in the repo if the CI errors
> server: enable connection test on macos

- analyzer/symbol.v
- server/tests/completion_test.v
- server/tests/hover_test.v
This PR makes fn decl don't show void when return void.
> analyzer: fn decl don't show void when return void

- analyzer/symbol.v
This PR fix method's receiver type is alias.
before:
now:
> analyzer: fix method's receiver type is alias

- analyzer/symbol.v
This PR don't show `void` when variable return_type is void for now.
> analyzer: don't show 'void' when variable return_type is void for now

- server/diagnostics.v
- server/tests/diagnostics_test.v
- server/text_synchronization.v
- server/vls.v
This PR updates the implementation of v.vet diagnostics (https://github.com/vlang/vls/commit/3c82d373ef58d86c4ddbbd271b67a440da77e192) to utilize the recently merged "check only" mode from https://github.com/vlang/v/pull/11414 which will provide comprehensive diagnostics compared to the previous one.
Aside from that, it executes the diagnostics when opening aside from saving
Related: #204
> server: change v diagnostics to v -check

- analyzer/symbol.v
- server/tests/completion_test.v
- server/tests/hover_test.v
This PR makes struct/enum type showing full information.
> analyzer: struct/enum type show full information

- analyzer/symbol.v
- server/tests/completion_test.v
- server/tests/hover_test.v
This PR makes selector's left type don't show parentheses.
> analyzer: selector's left type don't show parentheses

- analyzer/store.v
This PR fix fn args are repeated several times (fix #188).
> analyzer: fix fn args are repeated several times (fix #188)

- analyzer/store.v
- analyzer/symbol.v
This PR uncomment some main free calls.
- `content.free()`, content is new file's content.
- `sb.free()`, strings.new_builder(100).
> analyzer: uncomment some main free calls

- cmd/vls/socket.v
This PR fix opening of big file with tcp mode.
- The default buffer io's size is 128*1024.
- It will cause error When opening big file, .e.g  checker.v.
- Increase the cache size to 1024*1024.
> vls: fix opening of big file with tcp mode

- README.md
Codespaces is not the same as the Web editor
> Fix Github product name

- analyzer/store.v
This PR fix fn_literal type detect (fix #167).
> analyzer: fix fn_literal type detect (fix #167)

- tree_sitter_v/grammar.js
This PR cleanup grammar.js in tree_sitter_v.
- Format grammar.js.
- Use `fn_keyword` instead of "fn" in `fn_literal`.
> tree_sitter_v: cleanup grammar.js

- README.md
- lsp/workspace.v
- server/testing/testing.v
- server/tests/test_files/workspace_did_change/changed_be_ignored.vv
- server/tests/test_files/workspace_did_change/should_be_deleted.vv
- server/tests/test_files/workspace_did_change/should_be_renamed.vv
- server/tests/workspace_did_change_test.v
- server/text_synchronization.v
- server/vls.v
- server/workspace.v
According to [LSP 3.15 Specification:](https://microsoft.github.io/language-server-protocol/specifications/specification-3-15/#workspace_didChangeWatchedFiles)
>
>The watched files notification is sent from the client to the server when the client detects changes to files watched by the language client. It is recommended that servers register for these file events using the registration mechanism. In former implementations clients pushed file events without the server actively asking for it.
>
>Servers are allowed to run their own file watching mechanism and not rely on clients to provide file events. However this is not recommended due to the following reasons:
>
> - to our experience getting file watching on disk right is challenging, especially if it needs to be supported across …
> server: implement workspace/didChangeWatchedFiles

- server/features.v
- server/tests/hover_test.v
This PR makes import mod don't show `as alias` when using no alias.
> server: import mod don't show as alias when using no alias

- analyzer/store.v
This PR disable invalid type report in analyzer.
- This parse type error is not a program error and should not be displayed.
> analyzer: disable invalid type report

- server/features.v
- server/tests/definition_test.v
According to the [documentation](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#textDocument_definition) the response should be an array of LocationLink objects.
I didn't find anything in the git logs as to why a single object was returned. So if you know why this was chosen, please feel free to close this PR. Thx.
Tested locally and VSCode still jumps to the right place.
```
[Trace - 12:19:22] Received request 'textDocument/definition - (6)'.
Params: {"jsonrpc":"2.0","id":6,"method":"textDocument/definition","params":{"textDocument":{"uri":"file:///d%3A/Repositories/eko/NppLspClient/tests/example2.v"},"position":{"line":8,"character":3}}}
[Trace - 12:19:22] Sending response 'textDocument/definition - (6)' took 0ms
Result: …
```
> change textDocument/definition response to array of LocationLink

- server/connection_test.v
- server/general_test.v
- server/tests/completion_test.v
- server/tests/definition_test.v
- server/tests/diagnostics_test.v
- server/tests/document_symbols_test.v
- server/tests/folding_range_test.v
- server/tests/formatting_test.v
- server/tests/hover_test.v
- server/tests/implementation_test.v
- server/tests/positions_test.v
- server/tests/regression_test.v
- server/tests/signature_help_test.v
- server/tests/workspace_did_change_test.v
- server/tests/workspace_symbols_test.v
- server/window_test.v
- test_utils/test_utils.v
- test_utils/test_utils_test.v
As preparation for an upcoming PR, this change will allow other modules outside of server module to utilize the useful testing utilities. This also makes loading test file paths configurable and not hardcoded unlike before.
> server: move `testing` module outside of server/, rename to `test_utils`

- server/diagnostics.v
- server/general_test.v
- server/text_synchronization.v
- server/vls.v
In preparation for #159 .
This PR adds two new feature enum members: `v_diagnostics` and `analyzer_diagnostics`. These are used for toggling which source to be used for displaying diagnostics into the editor. It also updates the `analyze` function and made it as a `Vls` method.
> server: add feature toggle for v diagnostics and analyzer diagnostics

- lsp/log/log.v
- server/general.v
- server/general_test.v
- server/vls.v
Closes #272 . It makes `set_logpath` return an option instead of panicing.  It also updates the `setup_logger` method and refactor some parts of general.v
> server, lsp/log: update log file creation handling

- server/features.v
- server/tests/signature_help_test.v
- server/tests/test_files/signature_help/empty_middle_arg.vv
- server/tests/test_files/signature_help/empty_second_arg.vv
- server/tests/test_files/signature_help/with_content.vv
- server/tests/test_files/signature_help/with_content_b.vv
This PR updates the signature help feature in which it is only activated before on empty arguments or after pressing comma and only points to the last index of the argument list. Now it points to the argument according to the position of the cursor. 
Closes #282.
> server: better implementation of signature help feature; add additional tests

- analyzer/store.v
- analyzer/symbol.v
- analyzer/symbol_registration_test.v
- analyzer/test_files/symbol_registration/fn_decl.test.txt
- analyzer/test_files/symbol_registration/type_decl.test.txt
This PR improves analysis of function type symbols and add tests related to it. Anonymous function types are not also registered immediately anymore inside the analyzer store but is instead stored into their respective parent symbols like typedefs or variables.
> analyzer: improve function type analysis, add tests

- analyzer/store.v
- analyzer/symbol_registration.v
- analyzer/test_files/symbol_registration/match_expr.test.txt
This PR adds support for analyzing match expressions when used inside a variable or a constant. This also includes adding `type_selector_expression` node to the `infer_value_type_from_node`
> analyzer: support for match expr analysis

- analyzer/store.v
- server/positions.v
- server/text_synchronization.v
- server/text_synchronization_test.v
- tree_sitter/tree_sitter.v
This PR implements numerous changes across the codebase:
- In tree-sitter, get_changed_ranges has been implemented for future use.
- Adding a new method for parsing source code with byte arrays.
- Refactor didOpen. Add comments
- Refactor didUpdate and add comments to avoid confusion.
- Update symbol scope on register_symbol
> server, analyzer, tree-sitter: improve didOpen/didUpdate; implement get_changed_ranges and parse_bytes

- .gitignore
- cmd/vls/host.v
- lsp/capabilities.v
- lsp/initialize.v
The documentLinkProvider(had bool now DocumentLinkOptions) and executeCommandProvider(had string now ExecuteCommandOptions) had the wrong types.
> Correct types in capabilities to match specs

- server/text_synchronization.v
I spotted that some files registered in `ls.files` have empty source and contain only single C.TSNode - (source_file [0, 0] - [0, 0]).
I think filenames coming from `os.ls` are always "just" filenames without path. Those filenames are used to read a file and it fails since current dir is probably where vls was started. I guess it could be fixed by changing current dir to `project_dir` or using full path to file (as i propose here).
As always LMK WDYT
> Use full path for initial source load

- build.vsh
- server/code_lens.v
- server/vls.v
Currently every time we switch document, vscode cancels previous request and requests new code lenses for newly focused document. I thought it would be nice to either:
1. reply with empty response 
OR
2. do not report code lenses capability to vs code
Since we probably want to have this capability in the future I thought I will go with option nr 1.
Let me know WDYT.
This functionality is currently implemented in separate file (code_lens.v) and I'm not sure if it is good practice or it should be in features.v file. Personally I think features.v file should be split into several smaller ones, but this is only my take on it.
> Add dummy code lens support

- analyzer/tree_walker.v
- server/features.v
Hello,
Previous implementation had a bug - there was swapped values for line and character.
```v
start_line: tsrange_to_lsp_range(named_child.range()).start.character
start_character: tsrange_to_lsp_range(named_child.range()).start.line
```
I started to investigate how to improve things and got carried away...
Let me know WDYT.
> Add code folding based on full tree sitter tree

- server/features.v
I a bit naively added this functionality and I'm not sure if this is in right place.
Also `symbol_to_completion_item(..)` function could be extended with embedded type name. I wasn't sure if this is necessary, but let me know if needed.
> Naive struct embedding autocompletion

- jsonrpc/server.v
- server/code_lens.v
- server/features.v
- server/general.v
- server/tests/completion_test.v
- server/tests/definition_test.v
- server/tests/document_symbols_test.v
- server/tests/folding_range_test.v
- server/tests/formatting_test.v
- server/tests/hover_test.v
- server/tests/implementation_test.v
- server/tests/workspace_did_change_test.v
- server/tests/workspace_symbols_test.v
- server/text_synchronization.v
- server/vls.v
- server/workspace.v
This PR moves all of the JSON parameter decoding from methods to `handle_jsonrpc`. No obvious advantages other than almost-simplified unit testing (more PRs to be done later to tackle this)
> server: move json param decoding to handle_jsonrpc, simplify tests

- analyzer/semantic_analyzer.v
- analyzer/test_files/semantic_analyzer/type_expression.test.txt
This PR is a cherry-picked portion of https://github.com/vlang/vls/pull/159.
Adds support for analyzing `type_declaration`.
> analyzer/semantic_analyzer: add support for `type_declaration`

- analyzer/semantic_analyzer.v
- analyzer/test_files/semantic_analyzer/assert_statement.test.txt
- analyzer/test_files/semantic_analyzer/assignment_statement.test.txt
- analyzer/test_files/semantic_analyzer/send_statement.test.txt
This PR is a cherry-picked portion of https://github.com/vlang/vls/pull/159.
Adds support for analyzing `assert_statement`, `send_statement`, and `assignment_statement` nodes.
> analyzer/semantic_analyzer: add support for `assert_statement`, `send_statement`, and `assignment_statement`

- README.md
- cmd/vls/host.v
- server/general.v
- server/general_test.v
- server/vls.v
This PR changes the output directory for report files and log files from the user's home directory to `<home dir>/.vls` with reports and logs have their own separate subdirectories respectively.
Closes #340.
> cmd/vls, server: change output directory for logs, reports

- analyzer/ast.v
- analyzer/imports.v
- analyzer/imports_test.v
- analyzer/semantic_analyzer.v
- analyzer/semantic_analyzer_compliance_test_.skipvv
- analyzer/semantic_analyzer_test.v
- analyzer/store.v
- analyzer/symbol_registration.v
- analyzer/symbol_registration_test.v
- analyzer/tree_cursor.v
- analyzer/tree_walker.v
- ast/parser.v
- server/ast.v
- server/features.v
- server/file.v
- server/vls.v
Now https://github.com/vlang/v/issues/14718 is out of the way, this minor convenience can be applied. The following `tree_sitter` symbols are aliased:
- `tree_sitter.Node<v.NodeType>` => `ast.Node`
- `tree_sitter.Tree<v.NodeType>` => `ast.Tree`
> ast: rename `parser` module to `ast`, alias some tree sitter symbols

- ropes/ropes.v
- ropes/ropes_test.v
- server/features.v
- server/file.v
- server/text_synchronization.v
This PR implements a rope data structure based on https://github.com/vinzmay/go-rope . Before this, VLS uses `[]runes` directly and manipulates the buffer through a combination of `grow_len` and loop insertion which is not suitable. With this tree-like structure, we will be able to manipulate text buffers of files/documents in a proper manner.
> server: implement ropes for handling text buffers

- ropes/ropes.v
- ropes/ropes_test.v
This PR primarily reimplements the rebalancing feature of the rope data structure which is based on another rope implementation in Go by deadpixi (https://github.com/deadpixi/rope/blob/main/rope.go)
Also, the implementations for split and concat have been reimplemented based on the same implementation in order for the rebalancing to be possible.
> ropes: reimplement rebalancing concat, and split

- cmd/vls/main.v
- lsp/log/log.v
- lsp/log/log_test.v
This PR simplifies the code for the `lsp/log` module with the logging designed for `jsonrpc.Server` only. Including in this PR is the fix for the "incomplete log" bug when the server is closed unexpectedly by flushing the contents on each log.
> lsp/log: simplify code, fix "incomplete log" bug

- analyzer/semantic_analyzer.v
- analyzer/store.v
- analyzer/symbol_registration.v
- analyzer/tree_cursor.v
- server/text_synchronization.v
- server/vls.v
This PR improves analysis efficiency by only analyzing the affected AST nodes through its line number. Import analysis is now executed if the affected node is an import statement and semantic analysis is executed if its otherwise.
This will hopefully alleviate concerns surrounding #360.
> analyzer, server: partial symbol, import, and semantic analysis

- cmd/vls/host.v
Fixes #360. This PR fixes the increased CPU usage of host process on Windows caused by a "less used" select loop and a continuous logging of stderr regardless of its content. The offending code has been removed and `stderr_read` is replaced with `stderr_flush` so that it would only be logged if whenever it has content or is in EOF. 
Before the patch, CPU usage of the host process on standby ranges from 20% up to 45% compared to 0.5% to 6% after the patch.
The change shouldn't regress on platforms other than Windows.
> cmd/vls: fix child stderr output monitoring

- server/diagnostics.v
This PR fixes the server hang upon executing `executing_v_diagnostics` on `textDocument/didOpen` on Windows after opening a text document/file by running the process only and not wait for it to finish processing. 
This should not regress on platforms other than Windows.
> server: fix exec_v_diagnostics hang on Windows

- cmd/vls/main.v
- jsonrpc/server.v
- lsp/log/log.v
- server/general.v
- server/general_test.v
Fixes the issue when VLS sets up a log file even if `--debug` is set to false. This is caused by having a logic that a `LogRecorder` installed is automatically assumed that a logger is activated.
> server, jsonrpc, lsp/log: fix setup logger process

- cmd/vls/streams.v
- jsonrpc/server.v
- jsonrpc/server_test.v
- jsonrpc/server_test_utils/server_test_utils.v
- server/general_test.v
- test_utils/test_utils.v
this overrides the PR https://github.com/vlang/vls/pull/373 to revert the fmt changes, and I started to debug the CI failure but requires still some more love.
> vlib: migrate to the new reader API

- server/features_completion.v
- server/tests/completion_test.v
- server/tests/test_files/completion/abc/abc.v
- server/tests/test_files/completion/embedded_struct_field.vv
- server/tests/test_files/completion/enum_member.vv
- server/tests/test_files/completion/enum_method.vv
This PR fixes the following types of incomplete selector auto completions:
- Enums and it's members are not showing on top-level auto completion (when using from imports or not)
- Enum members not showing when enum type is already present (aka `EnumType.`)
- Embedded struct's fields are not showing when invoked on an incomplete selector
> server: fix enum and embedded field incomplete selector autocompletion

- analyzer/errors/formatter.v
- analyzer/errors/formatter_test.v
- analyzer/semantic_analyzer.v
In the upcoming versions of the V compiler, `v_sprintf` will not be available to the public. Thus, this PR is in preparation for that change without migrating existing analyzer error templates to other means such as string interpolation.
> analyzer/errors: fix sprintf deprecation, create custom error template compiler

- server/tests/completion_test.v
This is a fix related to the temporary [f218aea](https://github.com/vlang/vls/commit/f218aea557fa328f8fd851d7de3cccb13d14ca63) commit which skips the test due to invalid order of items which occurred yesterday.
> server/tests: fix flaky completion test

- jsonrpc/server_test_utils/server_test_utils.v
- server/tests/completion_test.v
- test_utils/test_utils.v
We really should investigate more why VLS stops at the first encountered `fn abc() !Type {`
It may be a grammar/tree sitter parser issue ?
> fix compilation with https://github.com/vlang/v/pull/16201

- lsp/lsp.v
- lsp/lsp_test.v
- server/diagnostics.v
- server/features.v
- server/features_completion.v
- server/general_test.v
- server/text_synchronization.v
- server/workspace.v
Fixing problem mentioned in [issue 407](https://github.com/vlang/vls/issues/407).
Rewrite methods of URI struct for better Windows URI support.
Adding normalize method call to all URI query for client request parameter.
Diagnostic report currently doesn't record correct file path, this pull request also fix that.
> Windows uri fix

- cmd/vls/streams.v
In [issue 401](https://github.com/vlang/vls/issues/401), having header(s) after Content-Length header will cause the whole rpc to fail. Because source code assumes Content-Length to be the last header.
This pull request fixes this bug.
> Fixing JSON-RPC header handling

- analyzer/imports.v
- ast/parser.v
To make AST and text synchronization debuging easier, add `str()` method to `ast.Node` type.
Example usage:
```v
import ast
fn log_ast(mut ls Vls, uri lsp.DocumentUri) {
file := ls.files[uri] or { return }
node := file.tree.root_node()
msg := '- * - Source - * -\n${file.source.string()}'
+ '\n- * - AST - * -\n${ast.Node(node)}'
+ '\n- * - Sexpr - * -\n${node}'
ls.writer.log_message(msg, .info)
}
```
Output:
```
- * - Source - * -
module main
import net.htp
fn main() {
test := 'this'
}
- * - AST - * -
module_clause *[0, 0] - [0, 11]
module_identifier *[0, 7] - [0, 11]
import_declaration *[2, 0] - [2, 14]
import_path *[2, 7] - [2, 14]
function_declaration *[4, 0] - [6, 1]
identifier *[4, 3] - [4, 7]
parameter_list *[4, 7] - [4, 9]
block *[4, 10] - [6, 1]
short_var_declaration *[5, 1] - [5, …
```
> Adding debug print support for ast.Node type

- jsonrpc/server.v
- server/vls.v
In LSP sepc, `textDocument/hover` is allow to return `null` as result. Currently VLS response with error when no hover infomation found. This should not be an error. Instead, VLS should response with `null` result.
> Response hover request with null when no infomation found.

- analyzer/context.v
- analyzer/report.v
- analyzer/store.v
- analyzer/symbol.v
- analyzer/symbol_registration.v
- build.vsh
To bring comfort to development, adding diagnostic message for errors in symbol registration phase.
Those messages will only be shown when VLS is compiled with `-d trace` flag.
Adding support to directly pass parameters to `v` for `build.vsh`. Now one can use `--` to separate arguments for `build.vsh` and `v` command called by this script.
For example, to build VLS with `trace` flag:
```
v run build.vsh clang -- -d trace
```
> Add trace diagnostics to symbol registration phase.

- analyzer/text.v
- structures/ropes/ropes.v
VLS uses `[]rune` for storing source code content in memory, but `tree_sitter.SourceText` interface uses byte index.
When source code contains non-ASCII characters, this implementation causes problem.
This PR is a quick and simple fix. An optimization for rope type is planed.
> Make `Rope.substr` method to index content with byte index.

- cmd/vls/host.v
- server/general.v
- server/general_test.v
> Move reports and logs to `os.cache_dir()`

- server/features.v
fix for https://github.com/vlang/v/issues/20069
related to https://github.com/vlang/v/pull/20101
> fix crlf modif on windows
