- lsp/formatting.v
- lsp/text_document.v
- vls/features.v
- vls/general.v
- vls/text_synchronization.v
- vls/vls.v
> Formatting

- lsp/initialize.v
- lsp/text_document.v
- vls/diagnostics.v
- vls/features.v
- vls/general.v
- vls/text_synchronization.v
- vls/vls.v
Includes simplifications in formatting feature as well as making Document URIs the standard map keys in some of the fields
> vls: implement textDocument/didClose

- vls/general.v
- vls/vls.v
remove params from exit function
> Several changes to implement exit and shutdown

- vls/diagnostics.v
- vls/features.v
- vls/text_synchronization.v
- vls/vls.v
extracted from implement-autcompletion branch
> vls: use []byte when storing source

- vls/features.v
- vls/general_test.v
- vls/window_test.v
CI will fail because generics are still in PR: https://github.com/vlang/v/pull/8231
But the generics branch will be merged if the CI is green which needs to merge this branch.
I tested it locally and it worked. (But i don't know if the change of insert_text works properly, don't know how to test that, don't we have a test for it?).
i also moved the tests because i got this:
> vls: add fix for multiple generics

- cmd/vls/stdio.v
- vls/features.v
- vls/text_synchronization.v
- vls/workspace.v
Required for https://github.com/vlang/v/pull/8471
> all: remove unused params

- cmd/vls/main.v
- vls/general_test.v
- vls/tests/completion_test.v
- vls/tests/diagnostics_test.v
- vls/tests/document_symbols_test.v
- vls/tests/formatting_test.v
- vls/tests/workspace_symbols_test.v
- vls/window_test.v
> vls: fix casting non-pointer types to interfaces

- vls/features.v
- vls/general.v
- vls/general_test.v
- vls/tests/completion_test.v
- vls/tests/diagnostics_test.v
- vls/tests/document_symbols_test.v
- vls/tests/folding_range_test.v
- vls/tests/formatting_test.v
- vls/tests/hover_test.v
- vls/tests/positions_test.v
- vls/tests/workspace_symbols_test.v
- vls/text_synchronization.v
> vls: migrate to the new error syntax

- vls/diagnostics.v
- vls/features.v
- vls/positions.v
- vls/tests/positions_test.v
Removes the need to calculate columns using the source as https://github.com/vlang/v/pull/#9407 was already merged. Still waiting for https://github.com/vlang/v/pull/9432 to be merged in order for the tests to succeed.
> vls: update position utils

- vls/features.v
- vls/tests/folding_range_test.v
> vls: implement fix for vlang/v#9647

- cmd/vls/stdio.v
- jsonrpc/jsonrpc.v
- lsp/log/log.v
Fix for VLS compilation, if/when https://github.com/vlang/v/pull/10263 is merged.
It also fixes compilation with `v -cstrict -cc clang-11 cmd/vls/`
> fix compilation with V PR#10263

- README.md
Fix the documentation and explain the proper location for the VLS executable.
> Update instructions for custom VLS executable path

- lsp/signature_help.v
- vls/features.v
- vls/vls.v
To be followed by myself on subsequent pull requests, just I thought it would get big if I don't go little by little
> Initial work on signature help support

- analyzer/analyzer.v
- analyzer/store.v
- lsp/signature_help.v
- vls/features.v
- vls/text_synchronization.v
After this will start working on making the analyzer work
> features: Iron out signature help and wire with the analyzer

- analyzer/depgraph/depgraph.v
- analyzer/store.v
- analyzer/symbol.v
- lsp/signature_help.v
- vls/features.v
- vls/tests/signature_help_test.v
- vls/vls.v
Reimplement #5 and PR #55 in tree-sitter. Closes #5
> vls: reimplement textDocument/signatureHelp in tree-sitter

- analyzer/builtin.v
- analyzer/store.v
- analyzer/symbol.v
- analyzer/symbol_registration.v
- vls/features.v
- vls/general.v
This PR fixes the issues caused by the [grammar rewrite](https://github.com/nedpals/tree-sitter-v/pull/8). It also includes the fixes from the autocompletion PR.
> vls: Implement fixes for grammar rewrite

- .github/workflows/prerelease.yml
- Support for MacOS added
- Latest commit creates a pre-release
> Improve CI

- .github/workflows/ci.yml
- analyzer/analyzer.v
- analyzer/ast.v
- analyzer/builtin.v
- analyzer/imports.v
- analyzer/imports_misc.v
- analyzer/imports_test.v
- analyzer/scope.v
- analyzer/store.v
- analyzer/symbol.v
- analyzer/symbol_registration.v
- cmd/vls/main.v
- cmd/vls/socket.v
- cmd/vls/stdio.v
- lsp/completion.v
- lsp/signature_help.v
- tree_sitter_v/bindings.v
- tree_sitter_v/bindings/v/bindings.v
- vls/connection_test.v
- vls/general.v
- vls/testing/testing.v
- vls/tests/definition_test.v
- vls/tests/test_files/connection/hello.vv
- vls/vls.v
- Fixes the TCP server reusing one connection for the whole session.
- Add `connection_test.v`
- Formatted codebase
To use it on VSCode, use the branch in this PR: https://github.com/vlang/vscode-vlang/pull/283
> vls: Fix TCP connection implementation

- lsp/log/log.v
This PR fix log duplication problems.
> log: fix log duplication problems

- lsp/log/log.v
This PR remove extra blank lines.
```vlang
[Trace - 20:21:32] Sending notification 'window/showMessage'.
Params: {"jsonrpc":"2.0","method":"window/showMessage","params":{"type":2,"message":"VLS is a work-in-progress, pre-alpha language server. It may not be guaranteed to work reliably due to memory issues and other related factors. We encourage you to submit an issue if you encounter any problems."}}
[Trace - 20:21:32] Received notification 'window/showMessage'.
Params: {"jsonrpc":"2.0","method":"window/showMessage","params":{"type":2,"message":"VLS is a work-in-progress, pre-alpha language server. It may not be guaranteed to work reliably due to memory issues and other related factors. We encourage you to submit an issue if you encounter any problems."}}
[Trace - 20:21:32] Received …
```
> log: remove extra blank lines

- server/vls.v
This PR remove unnecessary simulate receive message.
```vlang
[Trace - 22:09:35] Sending notification 'window/showMessage'.
Params: {"jsonrpc":"2.0","method":"window/showMessage","params":{"type":2,"message":"VLS is a work-in-progress, pre-alpha language server. It may not be guaranteed to work reliably due to memory issues and other related factors. We encourage you to submit an issue if you encounter any problems."}}
[Trace - 22:09:35] Received request 'initialize - (0)'.
Params: {"jsonrpc":"2.0","id":0,"method":"initialize","params":{"processId":17080,"clientInfo":{"name":"Visual Studio Code","version":"1.59.1"},"locale":"zh-cn","rootPath":"d:\\Test\\v\\tt1","rootUri":"file:///d%3A/Test/v/tt1","capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true,"resourc …
```
> vls: remove unnecessary simulate receive message

- cmd/vls/socket.v
This PR fix vls socket comm error.
- It is also normal to use an asynchronous mode.
> socket: fix vls socket comm error

- README.md
This PR fix error of generating vls file directory in readme.md.
> readme: fix error of generating vls file directory in readme.md

- cmd/vls/socket.v
- server/connection_test.v
This PR cleanup the socket output message format.
```vlang
PS D:\vls> ./vls --socket --port 5007
Warning: TCP connection is used primarily for debugging purposes only
and may have performance issues. Use it on your own risk.
[vls] : Established connection at 127.0.0.1:5007
[vls] : Sent data : Content-Length: 290 | {"jsonrpc":"2.0","method":"window/showMessage","params":{"type":2,"message":"VLS is a work-in-progress, pre-alpha language server. It may not be guaranteed to work reliably due to memory issues and other related factors. We encourage you to submit an issue if you encounter any problems."}}
[vls] : Received data : Content-Length: 4718 | {"jsonrpc":"2.0","id":0,"method":"initialize","params":{"processId":16876,"clientInfo":{"name":"Visual Studio …
```
> cmd/vls: cleanup the socket output message format

- analyzer/imports.v
- analyzer/imports_misc.v
- lsp/lsp.v
- server/text_synchronization.v
This PR fix error of import analysis.
> analyzer: fix error of import analysis

- analyzer/symbol.v
- analyzer/symbol_registration.v
- server/tests/completion_test.v
- server/tests/document_symbols_test.v
- server/tests/hover_test.v
> analyzer: fix method str

- analyzer/imports_test.v
- analyzer/store.v
- analyzer/symbol_registration.v
This PR fix fn return void optional.
> analyzer: fix fn return void optional

- analyzer/store.v
- analyzer/symbol.v
- analyzer/symbol_registration.v
This PR makes minor cleanup and optimization in analyzer.
> analyzer: minor cleanup and optimization

- analyzer/symbol.v
This PR perfect symbol object free() in analyzer.
> analyzer: perfect symbol object free

- analyzer/scope.v
- analyzer/symbol.v
This PR perfect scope object free() and fix symbol object free() in analyzer.
> analyzer: perfect scope object free

- analyzer/store.v
- analyzer/symbol.v
> Revert "analyzer: uncomment some main free calls"

- analyzer/depgraph/depgraph.v
- analyzer/imports.v
- analyzer/report.v
- analyzer/scope.v
- analyzer/store.v
- analyzer/symbol.v
- analyzer/symbol_registration.v
- lsp/log/log.v
- server/features.v
- server/testing/testing.v
- server/text_synchronization.v
- server/vls.v
- tree_sitter/tree_sitter.v
This PR remove string clone when assigning.
> analyzer, server: remove string clone when assigning

- lsp/log/log.v
- server/vls.v
draft! don't merge yet , preparing for https://github.com/vlang/v/pull/11963
> fix usages of mut interface methods

- analyzer/store.v
- analyzer/symbol.v
- analyzer/symbol_registration.v
- server/features.v
- server/tests/completion_test.v
- server/tests/test_files/completion/binded_symbol.vv
- server/tests/test_files/completion/gfx/gfx.v
Closes #233 . This also fixes symbol registration for structs with attributes
> analyzer, server: fix struct init completion generation for binded structs

- analyzer/symbol_registration.v
- server/features.v
- server/tests/completion_test.v
- server/tests/definition_test.v
- server/tests/hover_test.v
- server/tests/test_files/completion/fn_literal.vv
- server/tests/test_files/definition/fn_literal.vv
- server/tests/test_files/hover/fn_literal.vv
Closes #168 . This PR fixes language features not recognizing the contents of the function literal (aka anonymous functions)
> analyzer, server: support for analyzing fn_literal variables

- cmd/vls/host.v
This PR add vls commit hash info in error report.
> cmd: add vls commit hash info in error report

- analyzer/scope.v
- analyzer/symbol_registration.v
- analyzer/test_files/symbol_registration/fn_decl.test.txt
This PR fixes analysis for if expression node and added support for unsafe and defer expression blocks.
> analyzer: fix if expr analysis + support for unsafe, defer exprs

- analyzer/imports_test.v
- analyzer/store.v
- analyzer/symbol.v
- analyzer/symbol_registration.v
- analyzer/symbol_registration_test.v
- analyzer/test_files/symbol_registration/const_decl.test.txt
- analyzer/test_files/symbol_registration/short_var_decl.test.txt
This PR enables the analyzer to unwrap any symbol that returns an optional type in the variables. This also includes unwrapping in an if statement.
> analyzer: optional type unwrapping to variables

- analyzer/scope.v
- analyzer/symbol.v
- analyzer/symbol_registration.v
- analyzer/test_files/symbol_registration/const_decl.test.txt
- analyzer/test_files/symbol_registration/short_var_decl.test.txt
This PR adds support for inferring return symbols in if expressions. Add unsafe expression test
> analyzer: if expr support, add unsafe expr test

- analyzer/symbol_registration.v
- analyzer/symbol_registration_test.v
- analyzer/test_files/symbol_registration/for_loop.test.txt
- analyzer/test_files/symbol_registration/short_var_decl.test.txt
This PR fixes support for analyzing for statements, adds support for analyzing call expr or blocks.
> analyzer: fix for loop analysis, analyze call expr or block

- analyzer/store.v
- analyzer/test_files/symbol_registration/fn_decl.test.txt
This PR fix analysis error of variadic parameter.
> analyzer: fix analysis error of variadic parameter

- .gitignore
- cmd/vls/host.v
- lsp/capabilities.v
- lsp/initialize.v
> Revert "Correct types in capabilities to match specs"

- server/code_lens.v
- server/features.v
avoids panicing in such situations
> check that array elements exist before using pop

- README.md
vls can be installed by vim-lsp-settings
> readme: add instruction for vim

- README.md
I found it really hard to setup v on neovim, and because of that i added a simple tutorial to the vls README.
If there are any problems with my push request please reach out to me on discord: Jotrorox#2399
> Neovim setup added to readme

- analyzer/store.v
This PR fix analyzer/store.v with the lastest v compiler.
> fix analyzer/store.v with the lastest v compiler

- analyzer/imports_test.v
- analyzer/semantic_analyzer_compliance_test_.skipvv
- analyzer/semantic_analyzer_test.v
- analyzer/store.v
- analyzer/symbol.v
- analyzer/symbol_registration_test.v
- lsp/log/log_test.v
- server/general_test.v
- server/tests/code_lens_test.v
- server/tests/completion_test.v
- server/tests/definition_test.v
- server/tests/diagnostics_test.v
- server/tests/document_link_test.v
- server/tests/document_symbols_test.v
- server/tests/folding_range_test.v
- server/tests/hover_test.v
- server/tests/implementation_test.v
- server/tests/regression_test.v
- server/tests/signature_help_test.v
- server/tests/workspace_did_change_test.v
- server/tests/workspace_symbols_test.v
- server/window_test.v
- structures/depgraph/depgraph_test.v
- structures/ropes/ropes_test.v
- test_utils/test_utils_test.v
This PR clean up test functions.
> clean up test functions

- structures/depgraph/depgraph.v
This PR fix structures/depgraph/depgraph.v with the latest v compiler.
> fix structures/depgraph/depgraph.v with the latest v compiler

- analyzer/semantic_analyzer_test.v
- server/general_test.v
- server/tests/folding_range_test.v
This PR fix returning err in test.
> fix returning err in test

- cmd/vls/main.v
This should be merged after https://github.com/vlang/v/pull/16123 .
> fix compilation with V from https://github.com/vlang/v/pull/16123

- server/tests/completion_test.v
This PR fix ci error of completion_test.v.
> fix ci error of completion_test.v

- server/features.v
- structures/ropes/ropes.v
Needed for https://github.com/vlang/v/pull/16872
> all: pub functions which are used in tests

- cmd/vls/streams.v
> Fix header handling problem for stdio mode

- analyzer/store.v
- analyzer/symbol_registration.v
- server/features_completion.v
This PR fix unsafe map with reference value.
> store: fix unsafe map with reference value

- analyzer/store.v
- server/features_completion.v
This PR remove unsafe for map index.
> analyzer, server: remove unsafe for map index

- analyzer/context.v
- analyzer/imports_misc.v
- analyzer/imports_test.v
- analyzer/scope.v
- analyzer/semantic_analyzer.v
- analyzer/store.v
- analyzer/symbol_registration.v
- ast/tree_walker.v
- jsonrpc/server.v
- jsonrpc/server_test_utils/server_test_utils.v
- server/diagnostics.v
- structures/depgraph/depgraph.v
- test_utils/test_utils.v
- update_tree_sitter.vsh
There are functions return result type by having option type in their signature. Considering option type and result type gonna be separate in the future, adapt all those option type returns into result type one.
> Change some option type into result type.

- analyzer/semantic_analyzer.v
- analyzer/symbol_registration.v
- analyzer/tree_cursor.v
- ast/tree_walker.v
- tree_sitter/tree_sitter.v
This PR fix option fn returning error in tree_sitter.v.
> fix option fn returning error in tree_sitter.v

- lsp/window.v
This change is needed to be updated with https://github.com/vlang/v/pull/17696 changes.
> enum: update enum declaration to encode as int

- server/tests/completion_test.v
- server/tests/definition_test.v
- server/tests/document_symbols_test.v
- server/tests/folding_range_test.v
- server/tests/formatting_test.v
- server/tests/hover_test.v
- server/tests/implementation_test.v
- server/tests/signature_help_test.v
This PR fix if guard errors in tests.
> tests: fix if guard errors

- jsonrpc/jsonrpc.v
Removes an unnecessary self import.
Fixes failing CI in https://github.com/vlang/v/pull/18431
> fix: remove self import
